server:
  port: 12101

spring:
  application:
    name: eureka-client
  cloud:
    nacos:
      username: nacos
      password: cquissE12!@
      discovery:
        server-addr: 192.168.3.225:30769
        namespace: local
#  cloud:
#    nacos:
#      discovery:
#        server‚Äêaddr: 127.0.0.1:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'


